version: 2

sources:
  - name: dummy_source
    database: dummy
    schema: "{{ target.schema }}"
    freshness:
      error_after: {count: 24, period: hour}
      filter: dayname(updatedat) not in ('Sunday', 'Monday')
    loaded_at_field: current_timestamp
    tables:
      - name: doesnt_exist
