version: 2

sources:
  - name: dbt_artifacts
    # database: "{{ var('dbt_artifacts_database', 'blah') }}" this is currently breaking databricks, see https://getdbt.slack.com/archives/CU4MRJ7QB/p1657887390206099
    schema: "{{ var('dbt_artifacts_schema', target.schema) }}"
    tables:
      - name: model_executions
        identifier: "{{ var('dbt_model_executions_table', 'model_executions') }}"
        columns:
          - name: command_invocation_id
            description: ""
          - name: node_id
            description: ""
          - name: was_full_refresh
            description: ""
          - name: thread_id
            description: ""
          - name: status
            description: ""
          - name: compile_started_at
            description: ""
          - name: query_completed_at
            description: ""
          - name: total_node_runtime
            description: ""
          - name: rows_affected
            description: ""
          - name: materialization
            description: ""
          - name: schema
            description: ""
          - name: name

      - name: tests
        identifier: "{{ var('dbt_tests_table', 'tests') }}"

      - name: test_executions
        identifier: "{{ var('dbt_test_executions_table', 'test_executions') }}"

      - name: models
        identifier: "{{ var('dbt_models_table', 'models') }}"

      - name: seeds
        identifier: "{{ var('dbt_seeds_table', 'seeds') }}"

      - name: exposures
        identifier: "{{ var('dbt_exposures_table', 'exposures') }}"

      - name: snapshots
        identifier: "{{ var('dbt_snapshots_table', 'snapshots') }}"
